### PR TITLE
Remove the exception listener

### PR DESCRIPTION
**Pull request by kimlai**
Follow up for https://github.com/lrqdo/RestProblemBundle/pull/6.

This listener is problematic because it cannot be called along with
Symfony's default Exception Listener. They both set a
`Response`, stopping the exception propagation through other listeners.

The problem is that Symfony's default exception listener is the one
doing both the logging of the exception *and* the rendering of the
error.

The most straightforward way of getting our logs back is to simply
remove this listener.

### BC breaks:

- The HTTP status code when an exception occurs is always 500. No more
  400 for `LogicException`s and 501 for `RuntimeException`s.
- The JSON response is not

  ```json
  {
    "title": "",
    "type": "/exception",
    "detail": ""
  }
  ```

  But

  ```json
  {
    "error": {
      "code":500,
      "message":"Internal Server Error"
    }
  }
  ```

  with an additional `exception` property when in dev.
- The `Content-Type` of the response is not `application/api-problem+json` but `application/json`

### Enhancements:

- We have logs for exceptions
- We have less code to maintain
- Symfony's listener can handle exceptions thrown when handling a previous exception.

### Drawbacks:

- we loose the stack trace formatting when in dev (but we still have the
  stack trace, only in raw `json_encode($exception->getTrace())` form.

Everything concerning form errors remains the same.

### CODE REVIEW

**Comment by kimlai** [comment]
Est-ce que quelqu'un de @lrqdo/front pourrait me confirmer que les "BC breaks" de cette PR ne cassent pas des choses dans le front ?

**Comment by trompette** [comment]
:+1: si c'est bon pour le front.

**Comment by rik** [comment]
I have no idea of the implications, but @Sinewyk and @jbcochery should.

**Comment by kimlai** [comment]
According to @jbcochery, HTTP status codes >= 400 are only handled [here](https://github.com/lrqdo/front-web/blob/master/app/scripts/app.js#L70..L85) and [here](https://github.com/lrqdo/front-web/blob/master/app/scripts/entities/_base/model.js#L187..L209), which show no problems with this change (according to me).

**Comment by trompette** [comment]
On pourrait créer une branche sur le back qui utilise cette PR et laisser passer la suite de test, non ?

**Comment by kimlai** [comment]
C'est exactement ce que j'allais faire :)

**Comment by nclavaud** [comment]
> Est-ce que quelqu'un de @lrqdo/front pourrait me confirmer que les "BC breaks" de cette PR ne cassent pas des choses dans le front ?

On doit vérifier aussi l'app iOS.

**Comment by kimlai** [comment]
> On doit vérifier aussi l'app iOS.

OMG.

**Comment by kimlai** [comment]
C'est probable que ça aille plus vite de faire une autre refacto qui garde la rétro-compatibilté....

**Comment by Sinewyk** [comment]
Worth it to try to remove it IMO. Could probably grep stuff/ask vincent about the iOS app.

**Comment by kimlai** [comment]
Pour une approche rétro-compatible https://github.com/lrqdo/RestProblemBundle/pull/8

**Comment by ceithir** [comment]
J'aime cette PR dans le principe, mais comme tout le monde, je vais la botter en touche parce que iOS.

**Comment by kimlai** [comment]
Since BC is an issue, let's not do that.

**Pull request closed without merging**
